{
 "title": "Orthanc",
 "tags": [ "Orthanc" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "sources", "label": "Sources", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Patients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_count_patients{job=\"$sources\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Studies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_count_studies{job=\"$sources\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Studies (Time Range)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(orthanc_count_studies{job=\"$sources\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_count_series{job=\"$sources\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_count_instances{job=\"$sources\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Instanses (Time Range)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(orthanc_count_instances{job=\"$sources\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_up_time_s{job=\"$sources\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage / Cache Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_disk_size_mb{job=\"$sources\"} * 1024 * 1024",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "title": "Disk Usage  (Time Range)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(orthanc_disk_size_mb{job=\"$sources\"}[$__range]) * 1024 * 1024",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  { "title": "Cache Usage %", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 5, "x": 6, "y": 6 } },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "orthanc_storage_create_duration_ms{job=\"$sources\"}",
     "legendFormat": "Creating time"
    },
    {
     "expr": "orthanc_storage_read_duration_ms{job=\"$sources\"}",
     "legendFormat": "Reading time"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_jobs_success{job=\"$sources\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "orthanc_jobs_completed{job=\"$sources\"}",
     "legendFormat": "Complated"
    },
    {
     "expr": "orthanc_jobs_running{job=\"$sources\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "orthanc_jobs_pending{job=\"$sources\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "orthanc_jobs_failed{job=\"$sources\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "SCP Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 13 },
   "targets": [
    {
     "expr": "orthanc_find_scp_duration_ms{job=\"$sources\"}",
     "legendFormat": "C-Find"
    },
    {
     "expr": "orthanc_move_scp_duration_ms{job=\"$sources\"}",
     "legendFormat": "C-Move"
    },
    {
     "expr": "orthanc_get_scp_duration_ms{job=\"$sources\"}",
     "legendFormat": "C-Get"
    }
   ]
  },
  {
   "title": "Active request",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_rest_api_active_requests{job=\"$sources\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rest API",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "orthanc_rest_api_duration_ms{job=\"$sources\"}",
     "legendFormat": "Rest duration"
    }
   ]
  },
  {
   "title": "Available http threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_available_http_threads_count{job=\"$sources\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available http threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 20 },
   "targets": [
    {
     "expr": "orthanc_available_http_threads_count{job=\"$sources\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Available dicom threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_available_dicom_threads{job=\"$sources\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available dcom threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "orthanc_available_dicom_threads{job=\"$sources\"}",
     "legendFormat": "Threads"
    }
   ]
  }
 ]
}