{
 "title": "My Dash",
 "time": { "from": "now/d+8h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Patients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orthanc_count_patients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New patients by x time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(orthanc_count_patients[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(orthanc_storage_create_duration_ms[1m])",
     "legendFormat": "Creating time"
    },
    {
     "expr": "avg_over_time(orthanc_storage_read_duration_ms[1m])",
     "legendFormat": "Reading time"
    }
   ]
  },
  {
   "title": "Active connections to the PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_index_active_connections_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available dicom threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_available_dicom_threads",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rest API",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "expr": "orthanc_rest_api_active_requests",
     "legendFormat": "Active request"
    },
    { "expr": "orthanc_rest_api_duration_ms", "legendFormat": "Rest duration" }
   ]
  },
  {
   "title": "Disk Usage / Cache Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orthanc_disk_size_mb * 1024 * 1024",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "orthanc_dicom_cache_size_mb * 1024 * 1024",
     "legendFormat": "Cache Usage"
    }
   ]
  },
  {
   "title": "Disk Usage from X time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(orthanc_disk_size_mb[$__range]) * 1024 * 1024",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "title": "Files stored in cache",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orthanc_dicom_cache_count", "legendFormat": "Files stores in cache" }
   ]
  },
  {
   "title": "Jobs",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orthanc_jobs_success", "legendFormat": "Success" },
    { "expr": "orthanc_jobs_completed", "legendFormat": "Complated" },
    { "expr": "orthanc_jobs_running", "legendFormat": "Running" },
    { "expr": "orthanc_jobs_pending", "legendFormat": "Pending" },
    { "expr": "orthanc_jobs_failed", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orthanc_up_time_s", "legendFormat": "__auto" }
   ]
  }
 ]
}